# Website configuratie
base_url = "https://gedichtenkoffer.nl"
title = "gedichtenkoffer"
description = "Zoek je gedichten over 't leven, over liefde, geboorte, of rouw? Klik door, snuffel bij de teksten. Ik zie je gauw! "
author = "Sonja Zuijdervelt"

# Techniesche instellingen
theme = "noobping"
compile_sass = false
build_search_index = true
minify_html = true
generate_sitemap = true
generate_feeds = true
generate_robots_txt = true

# categorieën, tabladen en (hoofd)mappen (in content)
taxonomies = [
    { name = "categories", rss = true },
    { name = "posts", rss = true }
]

# Techniesche instellingen
[markdown]
highlight_code = false
lazy_async_image = true

[extra]
# thema configuratie
webapp = true
theme_color = "#1976D2"
keywords = "gedichtenkoffer, gedichten, leven, seizoenen, liefde, geboorte, rouw, kerst, sinterklaas"
footer = "Dit gedicht mag onder vermelding van de auteur, Sonja Zuijdervelt, gebruikt/verspreid worden"
badge = "[![Gedichtenkoffer Up-to-date](https://github.com/gedichtenkoffer/gedichtenkoffer/actions/workflows/jekyll.yml/badge.svg)](https://github.com/gedichtenkoffer/gedichtenkoffer/actions/workflows/jekyll.yml)"
share = true
language = "nl"
search = "zoek"
categories = "categorieën"
posts = "gedichten"
not_found = "Pagina niet gevonden"
not_found_subtitle = "De pagina die u zoekt bestaat niet."
not_found_description = "De pagina die je zoekt bestaat niet of is verwijderd. Probeer het nog eens of ga terug naar de <a href=\"/\">startpagina</a>."
search_noscript = "<strong>JavaScript is uitgeschakeld in uw browser.</strong> Schakel JavaScript in om de zoekfunctionaliteit te gebruiken."